import {PAGE_PADDING} from '../theme/layout';
import React from 'react';
import {Alert,Image,ScrollView,Text,View} from 'react-native';
import {Action,Card,Empty,Header} from '../components/UI';
import {groupDuplicates} from '../services/categories';
import type {LibraryController} from '../hooks/useLibrary';
import type {Screenshot} from '../types';
import {useTheme} from '../theme';
export function Cleanup({vm,open}:{vm:LibraryController;open:(item:Screenshot)=>void}){const {colors:c}=useTheme();const groups=groupDuplicates(vm.items);const pending=vm.items.filter(x=>!x.hash||!x.visualHash).length;return <View style={{flex:1}}><Header title="Review duplicates" subtitle="Compare each suggested match before deleting."/><ScrollView contentContainerStyle={{padding:PAGE_PADDING,paddingBottom:24}}>{pending>0?<Card><Text style={{color:c.ink,marginBottom:10}}>Checking {pending} screenshots for duplicates. This may take a moment.</Text><Action icon="refresh" label="Check again" secondary onPress={()=>void vm.indexDuplicates()}/></Card>:null}{groups.length===0?<Empty icon="verified" title={pending?'Still checking':'No duplicates found'} body={pending?'Keep this screen open while images are checked.':'All accessible screenshots have been compared.'}/>:groups.map((group,i)=><Card key={`${group.kind}-${group.items[0].id}`}><Text style={{fontWeight:'700',color:c.ink,marginBottom:3}}>Group {i+1} · {group.kind==='exact'?'Exact file match':'Visually similar'}</Text><Text style={{fontSize:12,color:c.muted,marginBottom:9}}>{group.kind==='similar'?'Visual similarity is only a suggestion. Check text and details before removing anything.':`${group.items.length} files have matching contents.`}</Text>{group.items.map(item=><View key={item.id} style={{flexDirection:'row',alignItems:'center',gap:10,marginBottom:9}}><Image source={{uri:item.uri}} style={{width:54,height:54,borderRadius:9,backgroundColor:c.line}}/><View style={{flex:1}}><Text numberOfLines={1} style={{color:c.ink,fontWeight:'600'}} onPress={()=>open(item)}>{item.name}</Text><Text style={{color:c.muted,fontSize:12}}>{new Date(item.date).toLocaleDateString()} · {(item.size/1024).toFixed(0)} KB</Text></View><Action icon="delete-outline" label="Delete" secondary onPress={()=>Alert.alert('Delete this screenshot?','Review all copies first. Android will ask you to confirm permanent deletion.',[{text:'Keep',style:'cancel'},{text:'Continue',style:'destructive',onPress:()=>{void vm.remove(item).catch(e=>Alert.alert('Could not delete photo',e instanceof Error?e.message:String(e)))}}])}/></View>)}</Card>)}</ScrollView></View>}
