import React from 'react';
import {ActivityIndicator,Image,Pressable,Text,View} from 'react-native';
import Icon from '@react-native-vector-icons/material-icons';
import {PAGE_PADDING} from '../theme/layout';
import {useTheme} from '../theme';
import type {Screenshot} from '../types';
export function Action({label,icon,onPress,secondary=false,disabled=false}:{label:string;icon:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){const {colors:c}=useTheme();return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={{minHeight:40,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',backgroundColor:secondary?c.pale:c.accent,borderRadius:11,paddingHorizontal:12,paddingVertical:8,opacity:disabled ? 0.5 : 1}}><Icon name={icon as never} size={17} color={secondary?c.accent:c.onAccent}/><Text style={{fontWeight:'700',color:secondary?c.accent:c.onAccent,fontSize:13}}>{label}</Text></Pressable>}
export function Header({title,subtitle}:{title:string;subtitle?:string}){const {colors:c}=useTheme();return <View style={{backgroundColor:c.bg,paddingHorizontal:PAGE_PADDING,paddingTop:15,paddingBottom:13,borderBottomWidth:1,borderColor:c.line}}><Text style={{fontSize:23,letterSpacing:-0.6,fontWeight:'800',color:c.ink}}>{title}</Text>{subtitle?<Text style={{fontSize:12,color:c.muted,lineHeight:18,marginTop:3}}>{subtitle}</Text>:null}</View>}
export function Card({children}:{children:React.ReactNode}){const {colors:c}=useTheme();return <View style={{backgroundColor:c.surface,padding:13,borderRadius:17,marginBottom:10,borderWidth:1,borderColor:c.line}}>{children}</View>}
export function Empty({icon,title,body}:{icon:string;title:string;body:string}){const {colors:c}=useTheme();return <View style={{alignItems:'center',justifyContent:'center',padding:30,gap:7}}><Icon name={icon as never} size={36} color={c.accent}/><Text style={{fontSize:17,fontWeight:'700',color:c.ink}}>{title}</Text><Text style={{fontSize:13,lineHeight:20,color:c.muted,textAlign:'center'}}>{body}</Text></View>}
export function Tile({item,onPress,onFavorite}:{item:Screenshot;onPress:()=>void;onFavorite:()=>void}){const {colors:c}=useTheme();return <Pressable onPress={onPress} style={{width:'48.5%',backgroundColor:c.surface,borderRadius:14,overflow:'hidden',marginBottom:12,borderWidth:1,borderColor:c.line}}><Image source={{uri:item.uri}} style={{height:136,width:'100%',backgroundColor:c.line}}/><View style={{paddingHorizontal:9,paddingVertical:8,flexDirection:'row',alignItems:'center'}}><View style={{flex:1}}><Text numberOfLines={1} style={{color:c.ink,fontWeight:'700',fontSize:12}}>{item.name||'Screenshot'}</Text><Text style={{fontSize:11,color:c.muted,marginTop:2}}>{new Date(item.date).toLocaleDateString()} · {item.status}</Text></View><Pressable accessibilityLabel={item.favorite?'Remove favorite':'Add favorite'} accessibilityRole="button" onPress={onFavorite} hitSlop={8}><Icon name={item.favorite?'star':'star-border'} size={20} color={c.accent}/></Pressable></View></Pressable>}
export function Loading(){const {colors:c}=useTheme();return <ActivityIndicator size="large" color={c.accent} style={{padding:24}}/>}
